#!/usr/bin/env python3
"""Sync assets/logo.png into an inline base64 data URI in index.html.

WebGL refuses to upload a texture from an <img> it considers cross-origin,
and Chrome treats every file:// path as a unique origin -- so the 3D
scene's center logo disc can never load assets/logo.png as a texture when
index.html is opened directly (double-clicked) instead of served over
http(s). A data: URI has no such origin, so it works in every context.
Run this after logo.png changes:

    python scripts/inline_logo.py
"""
import base64
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOGO_PNG = ROOT / "assets" / "logo.png"
INDEX_HTML = ROOT / "index.html"

BLOCK_RE = re.compile(
    r"<!-- INLINE-LOGO:START.*?-->\s*"
    r"<script>\s*window\.__LOGO_DATA_URI__ = \".*?\";\s*</script>\s*"
    r"<!-- INLINE-LOGO:END -->",
    re.DOTALL,
)


def main():
    png_bytes = LOGO_PNG.read_bytes()
    data_uri = "data:image/png;base64," + base64.b64encode(png_bytes).decode("ascii")

    html = INDEX_HTML.read_text(encoding="utf-8")
    if not BLOCK_RE.search(html):
        print("Could not find INLINE-LOGO:START ... INLINE-LOGO:END block in index.html", file=sys.stderr)
        sys.exit(1)

    replacement = (
        "<!-- INLINE-LOGO:START — generated by scripts/inline_logo.py from assets/logo.png. "
        "Run that script after logo.png changes. Used as the 3D scene's logo-texture source "
        "(not the header <img>) so it works under file:// too, where WebGL treats "
        "assets/logo.png as cross-origin and refuses to texture it. Do not hand-edit. -->\n"
        "<script>\n"
        f"window.__LOGO_DATA_URI__ = \"{data_uri}\";\n"
        "</script>\n"
        "<!-- INLINE-LOGO:END -->"
    )

    new_html = BLOCK_RE.sub(replacement, html)
    if new_html == html:
        print("index.html already up to date with assets/logo.png")
        return

    INDEX_HTML.write_text(new_html, encoding="utf-8")
    print("Synced assets/logo.png into index.html's inline logo texture data URI.")


if __name__ == "__main__":
    main()
