#!/usr/bin/env python3
"""Sync data.json into the INLINE-DATA block in index.html.

data.json stays the single source of truth for site content; index.html's
inline <script id="site-data"> block is a fallback copy used only when
fetch('data.json') is blocked (e.g. opening index.html via file://). Run
this after every data.json edit to keep the two in sync:

    python scripts/inline_data.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_JSON = ROOT / "data.json"
INDEX_HTML = ROOT / "index.html"

BLOCK_RE = re.compile(
    r"<!-- INLINE-DATA:START.*?-->\s*"
    r"<script type=\"application/json\" id=\"site-data\">\n"
    r".*?\n"
    r"</script>\s*"
    r"<!-- INLINE-DATA:END -->",
    re.DOTALL,
)


def main():
    data = json.loads(DATA_JSON.read_text(encoding="utf-8"))
    html = INDEX_HTML.read_text(encoding="utf-8")

    if not BLOCK_RE.search(html):
        print("Could not find INLINE-DATA:START ... INLINE-DATA:END block in index.html", file=sys.stderr)
        sys.exit(1)

    payload = json.dumps(data, indent=2, ensure_ascii=False)
    replacement = (
        "<!-- INLINE-DATA:START — generated by scripts/inline_data.py from data.json. "
        "Run that script after editing data.json to keep this block in sync. It's a "
        "fallback the app uses only when fetch('data.json') fails (e.g. opening index.html "
        "via file://); data.json fetched over http(s) is still the live source used "
        "normally. Do not hand-edit. -->\n"
        "<script type=\"application/json\" id=\"site-data\">\n"
        f"{payload}\n"
        "</script>\n"
        "<!-- INLINE-DATA:END -->"
    )

    new_html = BLOCK_RE.sub(replacement, html)
    if new_html == html:
        print("index.html already up to date with data.json")
        return

    INDEX_HTML.write_text(new_html, encoding="utf-8")
    print("Synced data.json into index.html's inline fallback block.")


if __name__ == "__main__":
    main()
