#!/usr/bin/env python3
"""Prerender SEO-critical HTML from data.json + blogs/manifest.json.

The home page is a JS-rendered Three.js scene; at runtime applySeo() in
index.html rebuilds the head metadata, JSON-LD and the hidden #seo-content
mirror from data.json. Crawlers that don't execute JS would otherwise see
stale or near-empty markup, so this script bakes the same output into the
static files, inside generated marker blocks (same pattern as
inline_data.py's INLINE-DATA block):

  index.html        INLINE-SEO-HEAD     title/description/keywords/OG/Twitter/canonical
                    INLINE-LD-JSON      Organization + WebSite JSON-LD @graph
                    INLINE-SEO-CONTENT  full semantic content mirror (#seo-content)
  blogs/index.html  INLINE-BLOG-LIST    static post cards with real .html links

The runtime JS then merely refreshes identical content, so JS-rendering and
no-JS crawlers see the same thing. Run after every data.json copy/SEO edit
and after publishing or removing a blog post:

    python scripts/prerender_seo.py

The HTML builders here mirror applySeo() in index.html and the card
renderer in blogs/index.html — if you change the markup in one place,
change it in the other.
"""
import json
import re
import sys
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_JSON = ROOT / "data.json"
MANIFEST_JSON = ROOT / "blogs" / "manifest.json"
INDEX_HTML = ROOT / "index.html"
BLOG_INDEX_HTML = ROOT / "blogs" / "index.html"
SITEMAP_XML = ROOT / "sitemap.xml"

RERUN_NOTE = "Rerun after editing data.json or publishing/removing a blog post. Do not hand-edit."


def block_re(name):
    return re.compile(
        r"<!-- " + name + r":START.*?<!-- " + name + r":END -->",
        re.DOTALL,
    )


def wrap_block(name, body):
    return (
        f"<!-- {name}:START — generated by scripts/prerender_seo.py. {RERUN_NOTE} -->\n"
        f"{body}\n"
        f"<!-- {name}:END -->"
    )


def replace_block(html, name, body, path):
    pattern = block_re(name)
    if not pattern.search(html):
        print(f"Could not find {name}:START ... {name}:END block in {path.name}", file=sys.stderr)
        sys.exit(1)
    return pattern.sub(lambda _m: wrap_block(name, body), html)


def merge_blog_items(sections, manifest):
    """Mirror of the manifest merge in index.html's init() — blog posts become
    items of the 'blogs' section with real links to their static pages."""
    posts = sorted(manifest, key=lambda p: p["date"], reverse=True)
    blog_section = next((s for s in sections if s.get("id") == "blogs"), None)
    if blog_section is not None:
        blog_section["items"] = [
            {
                "label": p["title"],
                "detail": p.get("excerpt", ""),
                "link": f"blogs/{p['slug']}.html",
            }
            for p in posts
        ]


def build_head_block(site):
    seo = site["seo"]
    brand = site.get("brand", {})
    canonical = seo["canonicalUrl"]
    title = seo.get("title") or site["title"]
    description = seo.get("description", "")
    keywords = seo.get("keywords", [])
    keywords = ", ".join(keywords) if isinstance(keywords, list) else keywords
    image = seo.get("ogImage", "")
    site_name = f"{brand.get('name', '')} — Gweru Hub"

    lines = [
        f"<title>{escape(title)}</title>",
        f'<meta name="description" content="{escape(description, quote=True)}">',
        f'<meta name="keywords" content="{escape(keywords, quote=True)}">',
        f'<link rel="canonical" href="{escape(canonical, quote=True)}">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:url" content="{escape(canonical, quote=True)}">',
        f'<meta property="og:title" content="{escape(title, quote=True)}">',
        f'<meta property="og:description" content="{escape(description, quote=True)}">',
        f'<meta property="og:image" content="{escape(image, quote=True)}">',
        f'<meta property="og:image:alt" content="{escape(seo.get("ogImageAlt", ""), quote=True)}">' if seo.get("ogImageAlt") else None,
        f'<meta property="og:locale" content="{escape(seo.get("locale", "en_ZW"), quote=True)}">',
        f'<meta property="og:site_name" content="{escape(site_name, quote=True)}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{escape(title, quote=True)}">',
        f'<meta name="twitter:description" content="{escape(description, quote=True)}">',
        f'<meta name="twitter:image" content="{escape(image, quote=True)}">',
        f'<meta name="twitter:image:alt" content="{escape(seo.get("ogImageAlt", ""), quote=True)}">' if seo.get("ogImageAlt") else None,
    ]
    if seo.get("twitterHandle"):
        lines.append(f'<meta name="twitter:site" content="{escape(seo["twitterHandle"], quote=True)}">')
    return "\n".join(l for l in lines if l)


def build_jsonld_block(site):
    """Mirror of the @graph applySeo() builds in index.html (same @ids, so the
    runtime reuses this <script id="ld-json"> instead of adding a second one)."""
    seo = site["seo"]
    canonical = seo["canonicalUrl"]
    title = seo.get("title") or site["title"]
    description = seo.get("description", "")
    image = seo.get("ogImage", "")
    brand_name = site.get("brand", {}).get("name", "")

    graph = [
        {
            "@type": "Organization",
            "@id": canonical + "#organization",
            "name": f"{brand_name} — Gweru Hub",
            "alternateName": ["Young AI Leaders Gweru", "YAL Gweru Hub"],
            "url": canonical,
            "logo": {"@type": "ImageObject", "url": image},
            "description": description,
            "sameAs": ["https://luma.com/user/yailgweru"],
            "areaServed": {"@type": "Country", "name": "Zimbabwe"},
            "location": {
                "@type": "Place",
                "name": "Gweru",
                "address": {
                    "@type": "PostalAddress",
                    "addressLocality": "Gweru",
                    "addressRegion": "Midlands Province",
                    "addressCountry": "ZW",
                },
            },
            "knowsAbout": [
                "Artificial Intelligence", "Social Innovation", "Youth Empowerment",
                "Technology in Zimbabwe", "AI for Good", "Community Impact", "Ethical AI",
            ],
            "memberOf": {"@type": "Organization", "name": "AI for Good (ITU)"},
        },
        {
            "@type": "WebSite",
            "@id": canonical + "#website",
            "url": canonical,
            "name": title,
            "description": description,
            "publisher": {"@id": canonical + "#organization"},
            "inLanguage": "en-ZW",
        },
    ]
    payload = json.dumps({"@context": "https://schema.org", "@graph": graph}, indent=2, ensure_ascii=False)
    return f'<script type="application/ld+json" id="ld-json">\n{payload}\n</script>'


def build_seo_content(site, sections):
    """Mirror of the #seo-content builder in applySeo() in index.html."""
    seo = site["seo"]
    title = seo.get("title") or site["title"]
    h1 = seo.get("h1") or title
    description = seo.get("description", "")

    html = f"<h1>{escape(h1)}</h1><p>{escape(description)}</p>"
    if seo.get("intro"):
        html += f"<p>{escape(seo['intro'])}</p>"

    for s in sections:
        html += f'<section id="{escape(s["id"], quote=True)}"><h2>{escape(s["title"])} — {escape(s.get("sub", ""))}</h2><ul>'
        for item in s.get("items", []):
            label = escape(item.get("label", ""))
            if item.get("link"):
                heading = f'<a href="{escape(item["link"], quote=True)}">{label}</a>'
            else:
                heading = label
            html += f"<li><h3>{heading}</h3><p>{escape(item.get('detail', ''))}</p>"
            body = (item.get("more") or {}).get("body")
            if body and " ".join(body) != item.get("detail"):
                html += "<article><p>" + "</p><p>".join(escape(p) for p in body) + "</p></article>"
            html += "</li>"
        people = s.get("people")
        if people:
            for p in (people.get("leadership") or []) + (people.get("members") or []):
                bio = p.get("bio")
                bio_text = " ".join(bio) if isinstance(bio, list) else (bio or p.get("brief", ""))
                text = " — ".join(t for t in [p.get("role", ""), bio_text] if t)
                html += f"<li><h3>{escape(p.get('name', ''))}</h3><p>{escape(text)}</p></li>"
        html += "</ul></section>"

    return (
        '<main id="seo-content" class="sr-only" aria-label="Young AI Leaders Gweru Hub">\n'
        f"{html}\n"
        "</main>"
    )


def build_blog_grid(manifest):
    """Mirror of the card renderer in blogs/index.html — real .html hrefs so
    crawlers get followable links (JS upgrades clicks to the #blogs/<slug>
    reading panel). Image paths in the manifest are site-root relative, so
    they need a ../ prefix from within /blogs/."""
    posts = sorted(manifest, key=lambda p: p["date"], reverse=True)
    if not posts:
        return '<p class="empty">No posts yet — check back soon.</p>'
    cards = []
    for p in posts:
        tags = " ".join("#" + t for t in (p.get("tags") or [])[:3])
        meta = p["date"]
        if p.get("author"):
            meta += f" &middot; by {escape(p['author'])}"
        if tags:
            meta += f" &middot; {escape(tags)}"
        cards.append(
            f'<a class="card" href="{escape(p["slug"], quote=True)}.html" data-slug="{escape(p["slug"], quote=True)}">'
            f'<img src="../{escape(p["image"], quote=True)}" alt="{escape(p["title"], quote=True)}" loading="lazy">'
            f'<div class="card-body"><h2>{escape(p["title"])}</h2><p>{escape(p.get("excerpt", ""))}</p>'
            f'<div class="meta">{meta}</div></div></a>'
        )
    return "\n".join(cards)


def check_sitemap(manifest):
    """Non-fatal consistency warnings — sitemap.xml itself is owned by
    publish_blog.py, which appends entries at publish time."""
    sitemap = SITEMAP_XML.read_text(encoding="utf-8")
    for p in manifest:
        page = f"blogs/{p['slug']}.html"
        if page not in sitemap:
            print(f"WARNING: {page} is in blogs/manifest.json but missing from sitemap.xml")
    for loc in re.findall(r"<loc>https://yailgweru\.github\.io/(.*?)</loc>", sitemap):
        if loc and not (ROOT / loc).exists():
            print(f"WARNING: sitemap.xml lists /{loc} but that file does not exist")


def main():
    data = json.loads(DATA_JSON.read_text(encoding="utf-8"))
    manifest = json.loads(MANIFEST_JSON.read_text(encoding="utf-8"))
    site = data["site"]
    sections = data["sections"]
    merge_blog_items(sections, manifest)

    changed = []

    index_html = INDEX_HTML.read_text(encoding="utf-8")
    new_index = index_html
    new_index = replace_block(new_index, "INLINE-SEO-HEAD", build_head_block(site), INDEX_HTML)
    new_index = replace_block(new_index, "INLINE-LD-JSON", build_jsonld_block(site), INDEX_HTML)
    new_index = replace_block(new_index, "INLINE-SEO-CONTENT", build_seo_content(site, sections), INDEX_HTML)
    if new_index != index_html:
        INDEX_HTML.write_text(new_index, encoding="utf-8")
        changed.append("index.html")

    blog_html = BLOG_INDEX_HTML.read_text(encoding="utf-8")
    new_blog = replace_block(blog_html, "INLINE-BLOG-LIST", build_blog_grid(manifest), BLOG_INDEX_HTML)
    if new_blog != blog_html:
        BLOG_INDEX_HTML.write_text(new_blog, encoding="utf-8")
        changed.append("blogs/index.html")

    check_sitemap(manifest)

    if changed:
        print("Prerendered SEO blocks updated in: " + ", ".join(changed))
    else:
        print("Prerendered SEO blocks already up to date.")


if __name__ == "__main__":
    main()
